version: '3.8'

services:
  # Base de Datos única para los 10 microservicios
  db_mysql:
    image: mysql:8.0
    container_name: mysql_quickorder
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # Script para crear las 10 bases de datos al iniciar
      - ./init-db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  # MICROSERVICIOS

  ms-amdusuario:
    build:
      context: ./ms-admusuario # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-amdusuario
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-bodega:
    build:
      context: ./ms-bodega # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-bodega
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-boleta:
    build:
      context: ./ms-boleta # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-boleta
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-categoria:
    build:
      context: ./ms-categoria # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-categoria
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-productos:
    build:
      context: ./ms-productos # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-productos
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-proveedores:
    build:
      context: ./ms-proveedores # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-proveedores
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-reponer:
    build:
      context: ./ms-reponer # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-reponer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-reportes:
    build:
      context: ./ms-reportes # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-reportes
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-stock:
    build:
      context: ./ms-stock # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-stock
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql

  ms-ventas:
    build:
      context: ./ms-ventas # Ruta a la carpeta del hijo
      dockerfile: Dockerfile
    container_name: ms-ventas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql:3306/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    deploy:
      resources:
        limits:
          memory: 128M # Límite estricto para ahorrar RAM
    depends_on:
      - db_mysql


volumes:
  mysql_data: